bp_process/routes.py
from flask import Blueprint, session, render_template, request, current_app, redirect

from access import group_permission_validation, get_role
from sql_provider import SQLProvider
from usedatabase import work_with_db, update_db
from bp_process.utils import add_to_basket, clear_basket

process_app = Blueprint('process', __name__, template_folder='templates')

provider = SQLProvider('bp_process/sql')


@process_app.route('/')
def process_menu():
    context = {'group_permission_validation': group_permission_validation, 'role': get_role()}
    return render_template('process_menu.html', context=context)


@process_app.route('/vacancy', methods=['GET', 'POST'])
def vacancy():
    if request.method == 'GET':
        result, _ = work_with_db(current_app.config['DB_CONFIG'], provider.get('vacancy.sql'))
        schema = ['Название позиции', 'Дата открытия', 'Дата закрытия']
        context = {'schema': schema, 'data': result, 'role': get_role()}
        return render_template('vacancy_list.html', context=context)
    else:
        vac_id = request.form.get('id')
        update_db(current_app.config['DB_CONFIG'], provider.get('delete_interview_by_vac.sql', id=vac_id))
        update_db(current_app.config['DB_CONFIG'], provider.get('delete_vacancy.sql', id=vac_id))
        return redirect('/process/vacancy')


@process_app.route('/vacancy/add', methods=['GET', 'POST'])
def add_vacancy():
    if request.method == 'GET':
        return render_template('vacancy_add.html')
    else:
        position = request.form.get('position')
        date = request.form.get('date')
        update_db(current_app.config['DB_CONFIG'], provider.get('insert_vacancy.sql', position=position, date=date))
        return redirect('/process/vacancy')


@process_app.route('/candidate', methods=['GET', 'POST'])
def candidate():
    if request.method == 'GET':
        result, _ = work_with_db(current_app.config['DB_CONFIG'], provider.get('candidate.sql'))
        schema = ['Имя', 'Дата рождения', 'Образование']
        context = {'schema': schema, 'data': result, 'role': get_role()}
        return render_template('candidate_list.html', context=context)
    else:
        candidate_id = request.form.get('id')
        update_db(current_app.config['DB_CONFIG'], provider.get('delete_interview_by_candidate.sql', id=candidate_id))
        update_db(current_app.config['DB_CONFIG'], provider.get('delete_candidate.sql', id=candidate_id))
        return redirect('/process/candidate')


@process_app.route('/candidate/add', methods=['GET', 'POST'])
def add_candidate():
    if request.method == 'GET':
        return render_template('candidate_add.html')
    else:
        name = request.form.get('name')
        birthday = request.form.get('birthday')
        education = request.form.get('education')
        update_db(current_app.config['DB_CONFIG'],
                  provider.get('insert_candidate.sql', name=name, birthday=birthday, education=education))
        return redirect('/process/candidate')


@process_app.route('/interview', methods=['GET', 'POST'])
def interview():
    if request.method == 'GET':
        result, _ = work_with_db(current_app.config['DB_CONFIG'], provider.get('interview.sql'))
        schema = ['Дата', 'Название позиции', 'Кандидат', 'Собеседующий', 'Результат собеседования']
        context = {'schema': schema, 'data': result, 'role': get_role()}
        return render_template('interview_list.html', context=context)
    else:
        interview_id = request.form.get('id')
        update_db(current_app.config['DB_CONFIG'], provider.get('delete_interview.sql', id=interview_id))
        return redirect('/process/interview')


@process_app.route('/interview/add', methods=['GET', 'POST'])
def add_interview():
    if request.method == 'GET':
        vac_sql = provider.get('open_vac.sql')
        open_vac, _ = work_with_db(current_app.config['DB_CONFIG'], vac_sql)
        hr, _ = work_with_db(current_app.config['DB_CONFIG'], provider.get('hr.sql'))
        candidates, _ = work_with_db(current_app.config['DB_CONFIG'], provider.get('candidate.sql'))
        basket = session.get('basket', [])
        return render_template('interview_add.html', open_vac=open_vac, hr=hr, candidates=candidates, items=candidates,
                               basket=basket, role=get_role())
    else:
        item_id = request.form.get('c_id')
        items, _ = work_with_db(current_app.config['DB_CONFIG'], provider.get('get_candidate.sql', id=item_id))
        if items:
            add_to_basket(items[0])
        return redirect('/process/interview/add')


@process_app.route('/interview/set', methods=['GET', 'POST'])
def basket_buy():
    basket = session.get('basket', [])
    if request.method == 'POST':
        date = request.form.get('date')
        v_id = request.form.get('v_id')
        e_id = request.form.get('e_id')
        for item in basket:
            sql = provider.get('insert_interview.sql', date=date, e_id=e_id, c_id=item['c_id'], v_id=v_id)
            update_db(current_app.config['DB_CONFIG'], sql)
        clear_basket()
        return redirect('/process/interview')


@process_app.route('/interview/clear')
def clear_basket_handler():
    clear_basket()
    return redirect('/process/interview/add')


@process_app.route('/interview/hire', methods=['GET', 'POST'])
def hire():
    if request.method == 'POST':
        i_id = request.form.get('i_id')
        result = request.form.get('result')
        if result == 'applied':
            sql = provider.get('candidate_by_interview.sql', i_id=i_id)
            item, _ = work_with_db(current_app.config['DB_CONFIG'], sql)
            name = item[0]['name']
            birthday = item[0]['birthday']
            education = item[0]['education']
            insert_employee = provider.get('insert_employee.sql', name=name, birthday=birthday, education=education)
            update_db(current_app.config['DB_CONFIG'], insert_employee)
            interview_result = provider.get('set_result_interview.sql', result=result, i_id=i_id)
            update_db(current_app.config['DB_CONFIG'], interview_result)
            return redirect('/process/interview')
        else:
            interview_result = provider.get('set_result_interview.sql', result=result, i_id=i_id)
            update_db(current_app.config['DB_CONFIG'], interview_result)
            return redirect('/process/interview')

bp_process/templates/candidate_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Добавить кандидата</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

<div class="d-flex justify-content-center mt-3">
    Добавить кандидата
</div>

<div class="container h-100 mt-3">
    <div class="row h-100 justify-content-center align-items-center">
        <form class="col-2" action="" method="post">
            <div class="form-group mb-3">
                <label for="name" class="form-text">Имя</label>
                <input class="form-control" type="text" name="name" id="name" required>
            </div>

            <div class="form-group mb-3">
                <label for="birthday" class="form-text">Дата рождения</label>
                <input class="form-control" type="date" name="birthday" id="birthday" required>
            </div>

            <div class="form-group mb-3">
                <label for="education" class="form-text">Образование</label>
                <input class="form-control" type="text" name="education" id="education" required>
            </div>

            <input class="btn btn-primary" type="submit" value="Добавить">
        </form>
    </div>
</div>

<div class="d-flex justify-content-center mt-3">
    <ul class="nav flex-column">
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('process.candidate') }}">Назад</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('index') }}">В главное меню</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('exit_system') }}">Выход</a>
        </li>
    </ul>
</div>
</body>
</html>

bp_process/templates/candidate_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Список вакансий</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
</head>

<style>
    table,
    td {
        text-align: center;
    }
</style>

<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">ИС Рекрутинг</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" href="/">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{{ url_for('process.process_menu') }}">Назад</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="/exit">Выход</a>
                </li>
            </ul>
            <div class="text-light">Вы авторизованы как {{ context.role }}</div>
        </div>
    </div>
</nav>

<div class="d-flex justify-content-center">
    <div class="d-inline-flex justify-content-center mt-3">Список кандидатов</div>
</div>

<div class="row justify-content-center mt-3">
    <div class="col-auto">
        <table class="table table-bordered">
            <tr>
                {% for item in context['schema'] %}
                    <td> {{ item }} </td>
                {% endfor %}
                <td></td>
            </tr>
            {% for dictionary in context['data'] %}
                <tr>
                    <td>{{ dictionary['name'] }}</td>
                    <td>{{ dictionary['birthday'] }}</td>
                    <td>{{ dictionary['education'] }}</td>

                    <td>

                        <form action="" method="post">
                            <input type="hidden" name="id" value="{{ dictionary['c_id'] }}">
                            <input type="submit" class="btn btn-primary" value="Удалить">
                        </form>

                    </td>

                </tr>
            {% endfor %}
        </table>
    </div>
</div>

<div class="d-flex justify-content-center mt-3">
    <form action="{{ url_for('process.add_candidate') }}">
        <input type="submit" class="btn btn-primary" value="Добавить кандидата">
    </form>
</div>

</body>
</html>

bp_process/templates/interview_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Назначить собеседование</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</head>
<body>

{% import 'util.html' as utils %}

<div class="d-flex justify-content-center mt-3">
    Назначить собеседование
</div>

<div class="container h-100 mt-3">
    <div class="row h-100 justify-content-center align-items-center">
        <form id="interview_form" class="col-5" action="/process/interview/set" method="post">
            <div class="form-group mb-3">
                <label for="date" class="form-text">Дата собеседования</label>
                <input class="form-control" type="date" name="date" id="date" required>
            </div>

            <div class="form-group mb-3">
                <label for="v_id" class="form-text">Вакансия</label>
                <select class="form-control" id="v_id" name="v_id">
                    {% for item in open_vac %}
                        <option value="{{ item['v_id'] }}">{{ item['vac_name'] }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="form-group mb-3">
                <label for="e_id" class="form-text">Собеседующий</label>
                <select class="form-control" id="e_id" name="e_id">
                    {% for item in hr %}
                        <option value="{{ item['id'] }}">{{ item['name'] }}</option>
                    {% endfor %}
                </select>
            </div>
        </form>
    </div>
</div>

{% import 'util.html' as utils %}

<div class="container h-50">
    <div class="row">
        <div class="col-md-5">
            <h2>Список кандидатов</h2>
            {% if items %}
                {% for item in items %}
                {{ utils.render_item(item, show_form=True) }}
                {% endfor %}
            {% else %}
                <p> Нет кандидатов </p>
            {% endif %}
        </div>

        <div class="col-md-5">
            <h2>Выбранные кандидаты</h2>
            {% if basket %}
                {% for item in basket %}
                {{ utils.render_item(item, show_form=False) }}
                {% endfor %}
            {% else %}
                <p> Нет выбранных кандидатов </p>
            {% endif %}
        </div>

        <div class="col-md-2">
            <a href="clear">Очистить выбранный список</a>
        </div>
    </div>
</div>

<div class="container h-100 mt-3">
    <div class="row h-100 justify-content-center align-items-center">
        <input class="btn btn-primary" type="submit" value="Назначить собеседование" form="interview_form">
    </div>
</div>

<div class="d-flex justify-content-center mt-3">
    <ul class="nav flex-column">
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('process.interview') }}">Назад</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('index') }}">В главное меню</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('exit_system') }}">Выход</a>
        </li>
    </ul>
</div>
</body>
</html>

bp_process/templates/interview_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Список собеседований</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
</head>

<style>
    table,
    td {
        text-align: center;
    }
</style>

<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">ИС Рекрутинг</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" href="/">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{{ url_for('process.process_menu') }}">Назад</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="/exit">Выход</a>
                </li>
            </ul>
            <div class="text-light">Вы авторизованы как {{ context.role }}</div>
        </div>
    </div>
</nav>

<div class="d-flex justify-content-center">
    <div class="d-inline-flex justify-content-center mt-3">Список собеседований</div>
</div>

<div class="row justify-content-center mt-3">
    <div class="col-auto">
        <table class="table table-bordered">
            <tr>
                {% for item in context['schema'] %}
                    <td> {{ item }} </td>
                {% endfor %}
                <td></td>
            </tr>
            {% for dictionary in context['data'] %}
                <tr>
                    <td>{{ dictionary['interview_date'] }}</td>
                    <td>{{ dictionary['vac_name'] }}</td>
                    <td>{{ dictionary['candidate'] }}</td>
                    <td>{{ dictionary['employee'] }}</td>

                    {% if not dictionary['result'] %}
                        <td>
                            <form action="/process/interview/hire" method="post">
                                <input type="hidden" name="i_id" value="{{ dictionary['i_id'] }}">
                                <label for="result" class="form-text">Результат</label>
                                <select class="form-control" id="result" name="result">
                                    <option value="rejected">Не принят</option>
                                    <option value="applied">Принят</option>
                                </select>
                                <br>
                                <input type="submit" class="btn btn-outline-primary btn-sm" value="Сохранить">
                            </form>
                        </td>
                    {% else %}
                        <td>{{ dictionary['result'] }}</td>
                    {% endif %}

                    <td>
                        <form action="" method="post">
                            <input type="hidden" name="id" value="{{ dictionary['i_id'] }}">
                            <input type="submit" class="btn btn-primary" value="Удалить">
                        </form>
                    </td>

                </tr>
            {% endfor %}
        </table>
    </div>
</div>

<div class="d-flex justify-content-center mt-3">
    <form action="{{ url_for('process.add_interview') }}">
        <input type="submit" class="btn btn-primary" value="Назначить собеседование">
    </form>
</div>
</body>
</html>

bp_process/templates/process_menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Меню запросов</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">ИС Рекрутинг</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" href="/">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="/exit">Выход</a>
                </li>
            </ul>
            <div class="text-light">Вы авторизованы как {{ context.role }}</div>
        </div>
    </div>
</nav>

<div class="d-flex justify-content-center">
    <div class="d-inline-flex justify-content-center mt-3">Прием сотрудников на работу</div>
</div>

<ul class="list-group align-content-center">

    {% if context.group_permission_validation('process.vacancy') %}
        <li class="list-group-item">
            <a class="nav-link" href="{{ url_for('process.vacancy') }}">Редактировать вакансии</a>
        </li>
    {% endif %}

    {% if context.group_permission_validation('process.candidate') %}
        <li class="list-group-item">
            <a class="nav-link" href="{{ url_for('process.candidate') }}">Редактировать список кандидатов</a>
        </li>
    {% endif %}

    {% if context.group_permission_validation('process.interview') %}
        <li class="list-group-item">
            <a class="nav-link" href="{{ url_for('process.interview') }}">Список собеседований</a>
        </li>
    {% endif %}

</ul>


</body>
</html>

bp_process/templates/util.html
{% macro render_item(candidate, show_form=False) %}
<div style="border-style: solid; border-color: blue; margin: 10px; padding: 10px">
    <p>
        <span>Имя: {{ candidate['name'] }}</span>
    </p>
    <p>
        <span>Дата рождения: {{ candidate['birthday'] }}</span>
    </p>
    <p>
        <span>Образование: {{ candidate['education'] }}</span>
    </p>
    {% if show_form %}
    <form action="" method="post">
        <input type="hidden" name="c_id" value="{{ candidate['c_id'] }}">
        <input class="btn btn-primary" type="submit" value="Добавить">
    </form>
    {% endif %}
</div>
{% endmacro %}

bp_process/templates/vacancy_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Добавить вакансию</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

<div class="d-flex justify-content-center mt-3">
    Добавить вакансию
</div>

<div class="container h-100 mt-3">
    <div class="row h-100 justify-content-center align-items-center">
        <form class="col-2" action="" method="post">
            <div class="form-group mb-3">
                <label for="position" class="form-text">Название позиции</label>
                <input class="form-control" type="text" name="position" id="position" required>
            </div>

            <div class="form-group mb-3">
                <label for="date" class="form-text">Дата открытия</label>
                <input class="form-control" type="date" name="date" id="date" required>
            </div>

            <input class="btn btn-primary" type="submit" value="Добавить">
        </form>
    </div>
</div>

<div class="d-flex justify-content-center mt-3">
    <ul class="nav flex-column">
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('process.vacancy') }}">Назад</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('index') }}">В главное меню</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('exit_system') }}">Выход</a>
        </li>
    </ul>
</div>
</body>
</html>

bp_process/templates/vacancy_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Список вакансий</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</head>

<style>
    table,
    td {
        text-align: center;
    }
</style>

<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">ИС Рекрутинг</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" href="/">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{{ url_for('process.process_menu') }}">Назад</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="/exit">Выход</a>
                </li>
            </ul>
            <div class="text-light">Вы авторизованы как {{ context.role }}</div>
        </div>
    </div>
</nav>

<div class="d-flex justify-content-center">
    <div class="d-inline-flex justify-content-center mt-3">Список вакансий</div>
</div>

<div class="row justify-content-center mt-3">
    <div class="col-auto">
        <table class="table table-bordered">
            <tr>
                {% for item in context['schema'] %}
                    <td> {{ item }} </td>
                {% endfor %}
                <td></td>
            </tr>
            {% for dictionary in context['data'] %}
                <tr>
                <td>{{ dictionary['vac_name'] }}</td>
                <td>{{ dictionary['open_date'] }}</td>
                <td>
                    {% if not dictionary['close_date'] %}
                    Вакансия открыта
                    {% else %}
                    {{ dictionary['close_date'] }}
                    {% endif %}
                </td>

                <td>

                    <form action="" method="post">
                        <input type="hidden" name="id" value="{{ dictionary['v_id'] }}">
                        <input type="submit" class="btn btn-primary" value="Удалить">
                    </form>

                </td>

                </tr>
            {% endfor %}
        </table>
    </div>
</div>

<div class="d-flex justify-content-center mt-3">
    <form action="{{ url_for('process.add_vacancy') }}">
        <input type="submit" class="btn btn-primary" value="Добавить вакансию">
    </form>
</div>

<div class="d-flex justify-content-center mt-3">
    <ul class="nav flex-column">
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('process.process_menu') }}">Назад</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('index') }}">В главное меню</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('exit_system') }}">Выход</a>
        </li>
    </ul>
</div>
</body>
</html>