bp_query/routes.py
from flask import Blueprint, render_template, request, current_app, session

import access
from sql_provider import SQLProvider
from usedatabase import work_with_db
from access import group_permission_decorator, group_permission_validation

query_app = Blueprint('query', __name__, template_folder='templates')

provider = SQLProvider('bp_query/sql')


@query_app.route('/')
@group_permission_decorator
def query_menu():
    context = {'group_permission_validation': group_permission_validation, 'role': access.get_role()}
    return render_template('query_menu.html', context=context)


@query_app.route('/interview')
@group_permission_decorator
def interview():
    employee_name = request.args.get('employee_name')
    date = request.args.get('date')
    if employee_name is None or date is None:
        return render_template('interview_form.html')
    else:
        year, month = date.split('-')
        sql = provider.get('interview.sql', name=employee_name, year=year, month=month)
        db_config = current_app.config['DB_CONFIG']
        result, schema = work_with_db(db_config, sql)
        context = {'schema': ['Дата интервью','Название вакансии', 'Имя кандидата', 'Результат', 'HR'], 'data': result}
        return render_template('interview_result.html', context=context)


@query_app.route('/vacancy')
@group_permission_decorator
def vacancy():
    date = request.args.get('date')
    if date is None:
        return render_template('vacancy_form.html')
    year, month = date.split('-')
    sql = provider.get('vacancy.sql', year=year, month=month)
    db_config = current_app.config['DB_CONFIG']
    result, schema = work_with_db(db_config, sql)
    context = {'schema': ['№', 'Название вакансии', 'Дата открытия вакансии', 'Количество дней, когда вакансия была свободна', 'Число кандидатов'], 'data': result}
    return render_template('vacancy_result.html', context=context)


@query_app.route('/young_employee')
@group_permission_decorator
def young_employee():
    year_month = request.args.get('date')
    if year_month is None:
        return render_template('young_employee_form.html')
    year, year_month = year_month.split('-')
    sql = provider.get('young_employee.sql', year=year, month=year_month)
    db_config = current_app.config['DB_CONFIG']
    result, schema = work_with_db(db_config, sql)
    context = {'schema': ['№', 'Имя', 'Дата рождения', 'Образование', 'Номер отдела', 'Дата приема на работу', 'Позиция', 'Оклад', 'Дата увольнения'], 'data': result}
    return render_template('young_employee_result.html', context=context)


@query_app.route('/employee')
@group_permission_decorator
def employee():
    date = request.args.get('date')
    if date is None:
        return render_template('employee_form.html')
    year, date = date.split('-')
    sql = provider.get('employee.sql', year=year, month=date)
    db_config = current_app.config['DB_CONFIG']
    result, _ = work_with_db(db_config, sql)
    context = {'schema': ['Имя'], 'data': result}
    return render_template('employee_result.html', context=context)

bp_query/templates/employee_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Форма запроса</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

<div class="d-flex justify-content-center mt-3">
    Показать сотрудников, которые не проводили собеседований в заднный год и месяц.
</div>

<div class="container h-100 mt-3">
    <div class="row h-100 justify-content-center align-items-center">
        <form class="col-2" action="" method="get">
            <div class="form-group mb-3">
                <label for="date" class="form-text">Выберите месяц и год</label>
                <input class="form-control" type="month" name="date" id="date" required>
            </div>
            <input class="btn btn-primary" type="submit" value="Получить данные">
        </form>
    </div>
</div>

<div class="d-flex justify-content-center mt-3">
    <ul class="nav flex-column">
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('query.query_menu') }}">Назад</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('index') }}">В главное меню</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('exit_system') }}">Выход</a>
        </li>
    </ul>
</div>
</body>
</html>

bp_query/templates/employee_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Результат запроса</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<style>
    table,
    td {
        text-align: center;
    }
</style>

<body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

<div class="row justify-content-center mt-3">
    <div class="col-auto">
        <table class="table table-bordered">
            <tr>
                {% for item in context['schema'] %}
                    <td> {{ item }} </td>
                {% endfor %}
            </tr>
            {% for dictionary in context['data'] %}
                <tr>
                    {% for value in dictionary.values() %}
                        <td> {{ value }} </td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>
    </div>
</div>

<div class="d-flex justify-content-center mt-3">
    <ul class="nav flex-column">
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('query.interview') }}">Назад</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('index') }}">В главное меню</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('exit_system') }}">Выход</a>
        </li>
    </ul>
</div>
</body>
</html>

bp_query/templates/interview_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Форма запроса</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

<div class="d-flex justify-content-center mt-3">
    Показать сведения о собеседованиях, проведенных сотрудником в заданный месяц
</div>

<div class="container h-100 mt-3">
    <div class="row h-100 justify-content-center align-items-center">
        <form class="col-2" action="" method="get">
            <div class="form-group mb-3">
                <label for="date" class="form-text">
                    Выберите месяц и год
                </label>
                <input type="month" name="date" id="date" required>
            </div>

            <div class="form-group mb-3">
                <label for="employee_name" class="form-text">
                    Введите имя сотрудника
                    <input type="text" name="employee_name" id="employee_name" required>
                </label>
            </div>

            <input class="btn btn-primary" type="submit" value="Получить данные">
        </form>
    </div>
</div>

<div class="d-flex justify-content-center">
    <ul class="nav flex-column">
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('query.query_menu') }}">Назад</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('index') }}">В главное меню</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('exit_system') }}">Выход</a>
        </li>
    </ul>
</div>
</body>
</html>

bp_query/templates/interview_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Результат запроса</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<style>
    table,
    td {
        text-align: center;
    }
</style>

<body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

<div class="row justify-content-center mt-3">
    <div class="col-auto">
        <table class="table table-bordered">
            <tr>
                {% for item in context['schema'] %}
                    <td> {{ item }} </td>
                {% endfor %}
            </tr>
            {% for dictionary in context['data'] %}
                <tr>
                    {% for value in dictionary.values() %}
                        <td> {{ value }} </td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>
    </div>
</div>

<div class="d-flex justify-content-center mt-3">
    <ul class="nav flex-column">
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('query.interview') }}">Назад</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('index') }}">В главное меню</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('exit_system') }}">Выход</a>
        </li>
    </ul>
</div>
</body>
</html>

bp_query/templates/query_menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Меню запросов</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


<div class="d-flex justify-content-center">
    <div class="d-inline-flex justify-content-center mt-3">Меню запросов</div>
</div>

<div class="d-flex justify-content-center">
    <div class="d-inline-flex justify-content-center mt-3">Вы авторизованы как {{ context.role }}</div>
</div>

<div class="d-flex justify-content-center mt-3">
    <ul class="nav flex-column">

        {% if context.group_permission_validation('query.interview') %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('query.interview') }}">Создать отчет о собеседованиях, проведенных
                    сотрудником в
                    заданный месяц</a>
            </li>
        {% endif %}

        {% if context.group_permission_validation('query.vacancy') %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('query.vacancy') }}">Создать отчет о вакансиях, открытых в заданный
                    месяц</a>
            </li>
        {% endif %}

        {% if context.group_permission_validation('query.young_employee') %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('query.young_employee') }}">Показать все сведения о самом молодом
                    сотруднике,
                    проводившем собеседование в заданный месяц</a>
            </li>
        {% endif %}

        {% if context.group_permission_validation('query.employee') %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('query.employee') }}">Показать сотрудников, которые не проводили
                    собеседований в
                    заднный
                    месяц</a>
            </li>
        {% endif %}

        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('index') }}">В главное меню</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('exit_system') }}">Выход</a>
        </li>
    </ul>
</div>
</body>
</html>

bp_query/templates/vacancy_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Форма запроса</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

<div class="d-flex justify-content-center mt-3">
    Показать сведения о вакансиях, открытых в заданный месяц.
</div>

<div class="container h-100 mt-3">
    <div class="row h-100 justify-content-center align-items-center">
        <form class="col-2" action="" method="get">
            <div class="form-group mb-3">
                <label for="date" class="form-text">
                    Введите месяц и год
                </label>
                <input class="form-control" type="month" name="date" id="date" required>
            </div>
            <input class="btn btn-primary" type="submit" value="Получить данные">
        </form>
    </div>
</div>

<div class="d-flex justify-content-center mt-3">
    <ul class="nav flex-column">
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('query.query_menu') }}">Назад</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('index') }}">В главное меню</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('exit_system') }}">Выход</a>
        </li>
    </ul>
</div>
</body>
</html>

bp_query/templates/vacancy_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Результат запроса</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<style>
    table,
    td {
        text-align: center;
    }
</style>

<body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

<div class="row justify-content-center mt-3">
    <div class="col-auto">
        <table class="table table-bordered">
            <tr>
                {% for item in context['schema'] %}
                    <td> {{ item }} </td>
                {% endfor %}
            </tr>
            {% for dictionary in context['data'] %}
                <tr>
                    {% for value in dictionary.values() %}
                        <td> {{ value }} </td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>
    </div>
</div>

<div class="d-flex justify-content-center mt-3">
    <ul class="nav flex-column">
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('query.interview') }}">Назад</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('index') }}">В главное меню</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('exit_system') }}">Выход</a>
        </li>
    </ul>
</div>
</body>
</html>

bp_query/templates/young_employee_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Форма запроса</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

<div class="d-flex justify-content-center mt-3">
    Показать все сведения о самом молодом сотруднике, проводившем собеседование в заданные месяц и год.
</div>

<div class="container h-100 mt-3">
    <div class="row h-100 justify-content-center align-items-center">
        <form class="col-2" action="" method="get">
            Выберите месяц и год
            <div class="form-group mb-3">
                <label for="date">
                    <input class="form-control" type="month" name="date" required>
                </label>
            </div>
            <input class="btn btn-primary" type="submit" value="Получить данные">
        </form>
    </div>
</div>

<div class="d-flex justify-content-center mt-3">
    <ul class="nav flex-column">
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('query.query_menu') }}">Назад</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('index') }}">В главное меню</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('exit_system') }}">Выход</a>
        </li>
    </ul>
</div>
</body>
</html>

bp_query/templates/young_employee_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Результат запроса</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<style>
    table,
    td {
        text-align: center;
    }
</style>

<body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

<div class="row justify-content-center mt-3">
    <div class="col-auto">
        <table class="table table-bordered">
            <tr>
                {% for item in context['schema'] %}
                    <td> {{ item }} </td>
                {% endfor %}
            </tr>
            {% for dictionary in context['data'] %}
                <tr>
                    {% for value in dictionary.values() %}
                        <td> {{ value }} </td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>
    </div>
</div>

<div class="d-flex justify-content-center mt-3">
    <ul class="nav flex-column">
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('query.interview') }}">Назад</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('index') }}">В главное меню</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('exit_system') }}">Выход</a>
        </li>
    </ul>
</div>
</body>
</html>